'use client';

import { motion } from 'framer-motion';

const steps = [
    {
        number: '01',
        title: 'Sign Up',
        description: 'Create your free account and set your exam goals.',
    },
    {
        number: '02',
        title: 'Take Assessment',
        description: 'Complete a quick diagnostic test to identify your strengths.',
    },
    {
        number: '03',
        title: 'Personalized Plan',
        description: 'Get a custom study schedule generated by our AI.',
    },
    {
        number: '04',
        title: 'Start Learning',
        description: 'Practice with mock tests, flashcards, and interactive lessons.',
    },
];

export function HowItWorks() {
    return (
        <section className="py-20 lg:py-32 bg-background">
            <div className="container mx-auto px-4">
                <div className="text-center mb-16">
                    <h2 className="text-3xl md:text-4xl font-bold mb-4">How It Works</h2>
                    <p className="text-muted-foreground">Four simple steps to start your journey to success.</p>
                </div>

                <div className="grid md:grid-cols-4 gap-8 relative">
                    {/* Connecting line (desktop only) */}
                    <div className="hidden md:block absolute top-8 left-0 w-full h-0.5 bg-muted -z-10" />

                    {steps.map((step, idx) => (
                        <motion.div
                            key={idx}
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: idx * 0.1 }}
                            className="relative bg-background pt-4 md:pt-0"
                        >
                            <div className="w-16 h-16 rounded-full bg-primary/10 border-4 border-background flex items-center justify-center text-xl font-bold text-primary mx-auto mb-6 relative z-10">
                                {step.number}
                            </div>
                            <h3 className="text-xl font-semibold text-center mb-3">{step.title}</h3>
                            <p className="text-center text-muted-foreground text-sm leading-relaxed">
                                {step.description}
                            </p>
                        </motion.div>
                    ))}
                </div>
            </div>
        </section>
    );
}
